### ISSUE TITLE
Controller Spawner couldn't find

### ISSUE THREAD

**Issue by Biruberuvinto** [chvmp/robots#1]
Hello.

This collection's robot can't stand when gazebo.launch started.
At that time, "Controller Spawner couldn't find the expected controller_manager ROS interface." is displayed in the terminal.

Is there a way to fix this issue?
![image](https://user-images.githubusercontent.com/51066397/92554146-9f9fe700-f29f-11ea-8758-0d6a22458209.png)

**Comment by grassjelly** [comment]
Hi this is related to https://github.com/chvmp/champ/issues/5 . This is because Anymal's URDF are missing the necessary tags to work in Gazebo. Currently there are only 4 robots that work in Gazebo:

- MIT's Mini Cheetah
- CHAMP's Default Model
- OpenQuadruped (https://github.com/adham-elarabawy/open-quadruped)
- OpenDog (https://github.com/XRobots/openDogV2)

**Comment by Biruberuvinto** [comment]
ok. I will attempt that models.
